server:
  port: 30000

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.255.155:8848
    alicloud:
      access-key: LTAI5tLfD3GZo2qKNZ9a7Lgb
      secret-key: fPmXL0uL0qpqvKKP6CnzcnAuKo4ITO
      oss:
        bucket: gulimall-ljf123
        endpoint: oss-cn-beijing.aliyuncs.com

logging:
  level:
    com.atguigu.gulimall.product: debug
